services:
  mongo_db:
    image: mongo
    networks:
      - mongo_net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secure_pw
    volumes:
      - ~/mai-data/database:/data/db

  training:
    build:
      context: .
      dockerfile: Dockerfile-training
    depends_on:
      - mongo_db
    networks:
      - mongo_net
    volumes:
      - ./data:/app/data
      - cache_torch:/root/.cache/torch
      - cache:/app/cache
      - ~/mai-data/databases/nytimes-images/images_processed/:/data/images
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  mongo_net:
    driver: bridge

volumes:
  cache:
  cache_torch:
