services:
  mongo_db:
    image: mongo
    networks:
      - mongo_net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secure_pw 
    volumes:
      - database:/data/db

  # mongo_restore:
  #   image: mongo
  #   depends_on:
  #     - mongo_db
  #   networks:
  #     - mongo_net
  #   # command: mongorestore --db nytimes --username root --password secure_pw --authenticationDatabase admin --host mongo_db --port 27017 --drop --archive=/dump/nytimes-2020-04-21
  #   command: mongorestore --db nytimes_sample --username root --password secure_pw --authenticationDatabase admin --host mongo_db --port 27017 --drop --gzip --archive=/dump/nytimes-2020-04-21_sample.gz
  #   volumes:
  #     - ./mongo_db/dump:/dump
  
  mongo_express:
    image: mongo-express
    depends_on: 
      - mongo_db
    networks:
      - mongo_net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secure_pw 
      ME_CONFIG_MONGODB_URL: mongodb://root:secure_pw@mongo_db:27017/
      ME_CONFIG_BASICAUTH: false

  # tnt-training:
  #   image: tnt-training
  #   depends_on:
  #     - mongo_db
  #   networks:
  #     - mongo_net
  #   volumes:
  #     - ./data:/app/data
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
networks:
  mongo_net:
    driver: bridge

volumes:
  database:
