services:
  mongo_db:
    image: mongo
    networks:
      - mongo_net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secure_pw
    volumes:
      - ~/mai-data/database:/data/db

  mongo_express:
    image: mongo-express
    depends_on:
      - mongo_db
    networks:
      - mongo_net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secure_pw
      ME_CONFIG_MONGODB_URL: mongodb://root:secure_pw@mongo_db:27017/
      ME_CONFIG_BASICAUTH: false

  scene-embedder:
    build:
      context: .
      dockerfile: Dockerfile-scene-embedder
    depends_on:
      - mongo_db
    networks:
      - mongo_net
    volumes:
      - ~/mai-data/databases/nytimes-images/images_processed/:/data/images/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1", "2", "3"]

networks:
  mongo_net:
    driver: bridge
